CREATE TABLE IF NOT EXISTS users (
    UserID INT AUTO_INCREMENT PRIMARY KEY,
    Username VARCHAR(50) NOT NULL UNIQUE,
    Password VARCHAR(255) NOT NULL,
    Role VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS authors (
    AuthorID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL
);

CREATE TABLE IF NOT EXISTS books (
    BookID INT AUTO_INCREMENT PRIMARY KEY,
    Title VARCHAR(100) NOT NULL,
    ISBN VARCHAR(20) NOT NULL UNIQUE,
    AuthorID INT NOT NULL,
    Genre VARCHAR(50),
    Availability BIT NOT NULL DEFAULT b'1',
    CONSTRAINT fk_books_author FOREIGN KEY (AuthorID) REFERENCES authors(AuthorID)
);

CREATE TABLE IF NOT EXISTS members (
    MemberID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    MembershipID VARCHAR(20) NOT NULL UNIQUE,
    UserID INT NOT NULL UNIQUE,
    CONSTRAINT fk_members_user FOREIGN KEY (UserID) REFERENCES users(UserID)
);

CREATE TABLE IF NOT EXISTS lendings (
    LendingID INT AUTO_INCREMENT PRIMARY KEY,
    BookID INT NOT NULL,
    MemberID INT NOT NULL,
    IssueDate DATETIME NOT NULL,
    DueDate DATETIME NOT NULL,
    ReturnDate DATETIME NULL,
    CONSTRAINT fk_lendings_book FOREIGN KEY (BookID) REFERENCES books(BookID),
    CONSTRAINT fk_lendings_member FOREIGN KEY (MemberID) REFERENCES members(MemberID)
);

CREATE TABLE IF NOT EXISTS notifications (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    MemberID INT NOT NULL,
    message VARCHAR(500) NOT NULL,
    overdue BIT NOT NULL DEFAULT b'0',
    sentAt DATETIME NOT NULL,
    CONSTRAINT fk_notifications_member FOREIGN KEY (MemberID) REFERENCES members(MemberID)
);
